using 'adf.bicep'

param privateEndpointName = 'myendpoint'
param vnetName = 'VNET'
param vnetAddressPrefix = '10.0.0.0/16'
param subnetName = 'subnet'
param subnetAddressPrefix = '10.0.0.0/18'
param privateDNSZoneName = 'privatelink.vaultcore.azure.net'
param dataFactoryName = 'ADFtaskhemangctsh'
param location = 'Central India'
